version: '3'

services:
  database:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0.6
    volumes:
      - volumeAlberto:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: ['--auth']
  dbmanager:
    depends_on:
      - database
    container_name: mongoExpress
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_NAME}
    restart: always
volumes:
  volumeAlberto:
    external: false